#!/usr/bin/env bash
# Regenerates src/esp32c6_fw_blob.h (gitignored) from Espressif's published
# esp_hosted slave firmware for the ESP32-C6. See issue #96 — this board's
# factory-programmed C6 co-processor firmware (2.3.2) is far older than what
# arduino-esp32 3.x's host driver expects, causing WiFi association to fail
# with AUTH_EXPIRE (known issue: espressif/esp-hosted-mcu#2). This blob feeds
# main_c6_flash_helper.cpp (env:remote_p4_c6_fw_update), a one-time repair
# sketch that pushes the update over the existing SDIO hosted link directly
# — no working WiFi needed, sidestepping the chicken-and-egg problem.
#
# Bump the version/URL if arduino-esp32's expected host version moves; check
# the "Update URL:" line the firmware itself prints at boot
# (esp32-hal-hosted.c's hostedHasUpdate() log) to confirm the current target.

set -euo pipefail
cd "$(dirname "$0")/.."

URL="https://espressif.github.io/arduino-esp32/hosted/esp32c6-v2.12.8.bin"
TMP="$(mktemp)"

curl -sL "$URL" -o "$TMP"
SIZE=$(stat -c%s "$TMP")
echo "Downloaded $SIZE bytes from $URL"

/usr/bin/python3 -c "
data = open('$TMP', 'rb').read()
assert data[0] == 0xE9, 'not a valid ESP32 image (bad magic byte)'
out = open('src/esp32c6_fw_blob.h', 'w')
out.write('// GENERATED by tools/fetch_c6_hosted_fw.sh -- gitignored, not source.\n')
out.write('// Source: $URL\n')
out.write('#pragma once\n#include <cstdint>\n')
out.write(f'constexpr uint32_t kC6FwBlobLen = {len(data)};\n')
out.write('constexpr uint8_t kC6FwBlob[] = {')
out.write(','.join(str(b) for b in data))
out.write('};\n')
out.close()
print('wrote src/esp32c6_fw_blob.h:', len(data), 'bytes')
"
rm -f "$TMP"
