#!/usr/bin/env python3
"""gen_ota_certs.py — regenerate src/ota_certs.h (issues #61/#62).

Inputs:
  1. A roots PEM file: the CA roots that anchor GitHub's HTTPS chains.
     Rebuild it when GitHub rotates CAs — check the live chains with
       openssl s_client -connect raw.githubusercontent.com:443 | grep i:
     then extract the named roots from the Mozilla bundle
     (https://curl.se/ca/cacert.pem). Comment lines between certs are fine.
  2. The OTA signing PUBLIC key (~/.slytherm/ota_signing_pub.pem by default) —
     the pair of the OTA_SIGNING_KEY_PEM CI secret. The private key never
     enters the repo.

Usage:
  python3 tools/gen_ota_certs.py <roots.pem> [pubkey.pem]
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "ota_certs.h"


def c_lit(text: str) -> str:
    return "\n".join('    "' + ln + '\\n"' for ln in text.strip().splitlines())


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    roots = Path(sys.argv[1]).read_text(encoding="utf-8")
    pub_path = (Path(sys.argv[2]) if len(sys.argv) > 2
                else Path(os.path.expanduser("~/.slytherm/ota_signing_pub.pem")))
    pub = pub_path.read_text(encoding="utf-8")
    if "BEGIN PUBLIC KEY" not in pub or "PRIVATE" in pub:
        sys.exit("gen_ota_certs.py: refusing — second input must be a PUBLIC key")

    hdr = (
        "// ota_certs.h — trust anchors for the OTA client (#61/#62). GENERATED by\n"
        "// tools/gen_ota_certs.py — regenerate rather than hand-edit.\n"
        "//\n"
        "// kOtaCaBundle: root CAs for GitHub HTTPS (github.com / raw.githubusercontent\n"
        "// .com / objects.githubusercontent.com). Live chains verified 2026-07-07:\n"
        "// ISRG Root X1 (Let's Encrypt, raw+objects) and USERTrust ECC (Sectigo,\n"
        "// github.com). The extra roots cover GitHub's historic/rotating CAs. mbedtls\n"
        "// parses the concatenated PEMs; comment lines between certs are tolerated.\n"
        "//\n"
        "// kOtaSigningPubKey: ECDSA-P256 public key matching the OTA_SIGNING_KEY_PEM\n"
        "// CI secret (private key held OUTSIDE the repo — ~/.slytherm on the dev box;\n"
        "// see #62). Firmware REJECTS any OTA image whose signature does not verify\n"
        "// against this key. Rotating the key = MAJOR version + dual-key window.\n"
        "\n"
        "#pragma once\n"
        "\n"
        "namespace ota_certs {\n"
        "\n"
        "constexpr const char kOtaCaBundle[] =\n"
        + c_lit(roots) + ";\n"
        "\n"
        "constexpr const char kOtaSigningPubKey[] =\n"
        + c_lit(pub) + ";\n"
        "\n"
        "}  // namespace ota_certs\n"
    )
    OUT.write_text(hdr, encoding="utf-8")
    print(f"gen_ota_certs.py: wrote {OUT} ({len(hdr)} bytes)")


if __name__ == "__main__":
    main()
